// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kogivmqdndcembqwbcri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvZ2l2bXFkbmRjZW1icXdiY3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDI3MDcsImV4cCI6MjA2MjkxODcwN30.fMjYJVps3TbAUxm840qnky5NLgNNqB5QF4x-F2P1zRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);